language: python
python:
  - "3.6.1"
  - "3.8"
  - "3.9"
before_install: pip install poetry
install: poetry install
script:
- poetry run isort --check main.py
- poetry run black --check main.py
- poetry run flake8 main.py
notifications:
  email: false
